#!/usr/bin/env bash
# scripts/smoke-abp-new.sh — local-only smoke for phase_abp_new.
# Runs the LinkHub-baseline combo against a real `abp new` + `dotnet build`.
# Slow (~3-7 min on first NuGet warm-up). NOT run in CI; see plan §11.
#
# Usage:
#   ./scripts/smoke-abp-new.sh                  # full smoke (real abp new + dotnet build)
#   ./scripts/smoke-abp-new.sh --flags-only     # skip the slow steps; flag-composition only
#   ABP_VERSION=10.3.0 ./scripts/smoke-abp-new.sh   # pin a specific ABP framework version

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ts="$(date +%s)"
smoke_dir="/tmp/abp-aidlc-template-smoke-$$-${ts}"
mkdir -p "$smoke_dir"

# Always clean up on EXIT (success or failure). Operator can
# `cp ${smoke_dir}/build.log /tmp/` BEFORE EXIT to preserve the log.
trap 'rm -rf "$smoke_dir"' EXIT

flags_only=0
if [[ "${1:-}" == "--flags-only" ]]; then
    flags_only=1
fi

# Minimal LinkHub-baseline config.
cat > "${smoke_dir}/smoke.yml" <<'EOF'
project_name: SmokeApp
github_owner: codarteinc
abp:
  template: app
  ui: angular
  db_provider: ef
  dbms: postgresql
  tiered: false
  multi_tenancy: false
  default_culture: en
  optional_modules: []
infra:
  hetzner_location: hel1
  hetzner_server_type: cx23
  cloudflare_zone: example.com
EOF

# 1. Flag-composition check (no abp invoked).
echo "--- flag composition (--dry-run-abp-new) ---"
bash "${ROOT}/scaffold.sh" \
    --config "${smoke_dir}/smoke.yml" \
    --target "${smoke_dir}/SmokeApp" \
    --dry-run-abp-new \
    > "${smoke_dir}/flags.log" 2>&1
cat "${smoke_dir}/flags.log"
flag_tokens=$(grep -c '^ABP_NEW_FLAG: ' "${smoke_dir}/flags.log" || true)
if (( flag_tokens < 17 )); then
    echo "FAIL: expected >= 17 ABP_NEW_FLAG tokens, got ${flag_tokens}" >&2
    exit 1
fi
echo "OK: ${flag_tokens} flag tokens assembled"

if (( flags_only == 1 )); then
    echo "OK: --flags-only — skipping real abp new / dotnet build"
    exit 0
fi

# 2. Real abp new (slow — NuGet download + framework restore).
echo "--- abp new (real) ---"
rm -rf "${smoke_dir}/SmokeApp"
if ! bash "${ROOT}/scaffold.sh" \
        --config "${smoke_dir}/smoke.yml" \
        --target "${smoke_dir}/SmokeApp" \
        > "${smoke_dir}/scaffold.log" 2>&1; then
    echo "FAIL: scaffold.sh failed; last 30 lines:" >&2
    tail -30 "${smoke_dir}/scaffold.log" >&2
    exit 1
fi
tail -10 "${smoke_dir}/scaffold.log"

# 3. dotnet build (slow — captures exit only, NOT the full log).
echo "--- dotnet build (real) ---"
# Prefer .slnx (the modern format abp 3+ generates) over .sln.
sln="$(find "${smoke_dir}/SmokeApp" -maxdepth 3 -name '*.slnx' | head -1)"
if [[ -z "$sln" ]]; then
    sln="$(find "${smoke_dir}/SmokeApp" -maxdepth 3 -name '*.sln' | head -1)"
fi
if [[ -z "$sln" ]]; then
    echo "FAIL: no .sln/.slnx generated by abp new" >&2
    find "${smoke_dir}/SmokeApp" -maxdepth 3 -type f | head -20 >&2
    exit 1
fi
if ! ( cd "$(dirname "$sln")" && dotnet build "$sln" > "${smoke_dir}/build.log" 2>&1 ); then
    echo "FAIL: dotnet build of generated solution failed; last 50 lines:" >&2
    tail -50 "${smoke_dir}/build.log" >&2
    exit 1
fi

# 4. unit-04 — spot-check the observability surface landed correctly in
#    the scaffolded tree. Validates that the OTel + health-endpoints +
#    Serilog blocks were spliced AND that the dotnet build above was
#    actually exercising them (rather than a tree without the overlays).
echo "--- observability surface spot-check (unit-04) ---"
host_module="$(find "${smoke_dir}/SmokeApp" -type f -name 'SmokeAppHttpApiHostModule.cs' | head -1)"
program_cs="$(find "${smoke_dir}/SmokeApp" -type f -name 'Program.cs' -path '*/SmokeApp.HttpApi.Host/*' | head -1)"
appsettings_json="$(find "${smoke_dir}/SmokeApp" -type f -name 'appsettings.json' -path '*/SmokeApp.HttpApi.Host/*' | head -1)"
host_csproj="$(find "${smoke_dir}/SmokeApp" -type f -name 'SmokeApp.HttpApi.Host.csproj' | head -1)"
for needle in 'AddOpenTelemetry()' 'MapPrometheusScrapingEndpoint' 'AddSmokeAppHealthChecks' 'HealthChecksPolicyName' 'AddMeter("SmokeApp.*")'; do
    if ! grep -qF "$needle" "$host_module"; then
        echo "FAIL: host module missing observability needle '$needle'" >&2
        exit 1
    fi
done
if ! grep -qF '.Enrich.WithSpan()' "$program_cs"; then
    echo "FAIL: Program.cs missing Serilog Enrich.WithSpan()" >&2
    exit 1
fi
if ! grep -qF '[trace={TraceId} span={SpanId}]' "$appsettings_json"; then
    echo "FAIL: appsettings.json missing [trace=... span=...] outputTemplate fragment" >&2
    exit 1
fi
if ! grep -qF 'Include="OpenTelemetry.Extensions.Hosting"' "$host_csproj"; then
    echo "FAIL: HttpApi.Host csproj missing OpenTelemetry.Extensions.Hosting" >&2
    exit 1
fi
echo "OK: observability surfaces present"

# 5. Unit-05 security-overlay assertions (post `dotnet build`).
echo "--- unit-05 security overlay assertions ---"
project_root="$(dirname "$sln")"

# 5a. CSP middleware file present + namespace token resolved.
csp_mw="$(find "$project_root" -path '*/Middleware/ContentSecurityPolicyMiddleware.cs' | head -1)"
if [[ -z "$csp_mw" ]]; then
    echo "FAIL: ContentSecurityPolicyMiddleware.cs not found under $project_root" >&2
    exit 1
fi
if grep -q '\${PROJECT_NAME}' "$csp_mw"; then
    echo "FAIL: \${PROJECT_NAME} not substituted in $csp_mw" >&2
    exit 1
fi

# 5b. Program.cs carries the production-fail-fast log line w/ substituted name.
prog="$(find "$project_root" -path '*/HttpApi.Host/Program.cs' | head -1)"
if ! grep -q '\[SmokeApp.Config\]' "$prog"; then
    echo "FAIL: production-fail-fast block not present (or PROJECT_NAME unsub'd) in $prog" >&2
    exit 1
fi

# 5c. appsettings.json has App:Csp:Mode == report-only.
appsettings="$(find "$project_root" -path '*/HttpApi.Host/appsettings.json' | head -1)"
if command -v jq >/dev/null; then
    mode="$(jq -r '.App.Csp.Mode' "$appsettings")"
    if [[ "$mode" != "report-only" ]]; then
        echo "FAIL: App.Csp.Mode != 'report-only' (got '${mode}') in $appsettings" >&2
        exit 1
    fi
fi

# 5d. All 4 dev secrets templates exist in rendered tree.
for tmpl in \
    "src/SmokeApp.HttpApi.Host/appsettings.secrets.json.template" \
    "src/SmokeApp.DbMigrator/appsettings.secrets.json.template" \
    "src/SmokeApp.HttpApi.Host/appsettings.Development.local.json.template" \
    "angular/src/environments/environment.local.ts.template"; do
    if [[ ! -f "${project_root}/${tmpl}" ]]; then
        # 5d-alt: angular path may not exist if scaffold uses different layout — soft-warn.
        if [[ "$tmpl" == angular/* && ! -d "${project_root}/angular" ]]; then
            echo "  (skip: ${tmpl} — no angular/ dir in this scaffold)"
            continue
        fi
        echo "FAIL: secret template missing: ${project_root}/${tmpl}" >&2
        exit 1
    fi
done

# 5e. generate-dev-openiddict-cert.sh executable + runs.
cert_script="${project_root}/etc/generate-dev-openiddict-cert.sh"
if [[ ! -x "$cert_script" ]]; then
    echo "FAIL: $cert_script is not executable" >&2
    exit 1
fi
OPENIDDICT_DEV_CERT_PASS=changeme PROJECT_NAME=SmokeApp \
    bash "$cert_script" >/dev/null
if [[ ! -s "${project_root}/src/SmokeApp.HttpApi.Host/openiddict.pfx" ]]; then
    echo "FAIL: dev cert script ran but openiddict.pfx absent or empty" >&2
    exit 1
fi
# Clean up so the smoke tmpdir trap doesn't carry crypto material around.
rm -f "${project_root}/src/SmokeApp.HttpApi.Host/openiddict.pfx"

# 6. Unit-06 docker-overlay assertions.
echo "--- unit-06 docker-overlay assertions ---"

# 6a. Compose files: structural shape via yq (always runs — yq is a hard
# scaffold.sh preflight dep). If docker is on PATH, also run
# `docker compose config` which catches YAML errors + missing-${VAR}
# references that lack a `:?` fallback.
for compose_f in docker-compose.yml docker-compose.dev.yml docker-compose.staging.yml; do
    if [[ ! -f "${project_root}/${compose_f}" ]]; then
        echo "FAIL: ${compose_f} missing from rendered tree" >&2
        exit 1
    fi
done

if command -v docker >/dev/null; then
    if ! ( cd "$project_root" && \
            APP_ENVIRONMENT=Development DB_PASSWORD=smoke API_PUBLIC_URL=https://api.localhost \
            WEB_PUBLIC_URL=https://localhost APP_API_HOSTNAME=api.localhost \
            APP_WEB_HOSTNAME=localhost \
            docker compose -f docker-compose.yml -f docker-compose.dev.yml config > /dev/null 2>&1 ); then
        echo "FAIL: base+dev compose config didn't parse" >&2
        exit 1
    fi
    if ! ( cd "$project_root" && \
            APP_ENVIRONMENT=Staging DB_PASSWORD=smoke API_VERSION=v1 WEB_VERSION=v1 \
            MIGRATOR_VERSION=v1 API_PUBLIC_URL=https://api.example.com \
            WEB_PUBLIC_URL=https://example.com APP_API_HOSTNAME=api.example.com \
            APP_WEB_HOSTNAME=example.com APP_ACME_EMAIL=ops@example.com \
            docker compose -f docker-compose.yml -f docker-compose.staging.yml config > /dev/null 2>&1 ); then
        echo "FAIL: base+staging compose config didn't parse" >&2
        exit 1
    fi
else
    echo "SKIP: docker not on PATH; compose config parse skipped (yq structural shape covered the basics)"
fi

# 6b. nginx.conf.template carries all 6 security directives + getEnvConfig + csp-report stub.
if [[ -f "${project_root}/angular/nginx.conf.template" ]]; then
    # The `$uri` in the try_files needle is literal nginx syntax — NOT
    # a shell expansion. shellcheck SC2016 is intentional here.
    # shellcheck disable=SC2016
    for needle in 'Content-Security-Policy-Report-Only' 'Strict-Transport-Security' 'X-Frame-Options "DENY"' \
                  'X-Content-Type-Options "nosniff"' 'Referrer-Policy' 'location = /csp-report' \
                  'location /getEnvConfig' 'try_files $uri /dynamic-env.json'; do
        if ! grep -qF "$needle" "${project_root}/angular/nginx.conf.template"; then
            echo "FAIL: nginx.conf.template missing needle: $needle" >&2
            exit 1
        fi
    done
else
    echo "SKIP: angular/nginx.conf.template not present (UI=none?); nginx surface assertions skipped"
fi

# 6c. .env has the dev-safe OPENIDDICT_DEV_CERT_PASS + DB_PASSWORD defaults
# (project name SmokeApp -> lowercase 'smokeapp').
if ! grep -q '^OPENIDDICT_DEV_CERT_PASS=smokeapp-dev-cert-pass' "${project_root}/.env"; then
    echo "FAIL: .env missing token-substituted OPENIDDICT_DEV_CERT_PASS default" >&2
    exit 1
fi
if ! grep -q '^DB_PASSWORD=smokeapp-dev' "${project_root}/.env"; then
    echo "FAIL: .env missing token-substituted DB_PASSWORD default" >&2
    exit 1
fi

# 6d. Caddyfile.dev references the project-prefixed hostname env vars.
if ! grep -qE '\$\{?APP_(API|WEB)_HOSTNAME\}?' "${project_root}/Caddyfile.dev"; then
    echo "FAIL: Caddyfile.dev missing APP_(API|WEB)_HOSTNAME env-var references" >&2
    exit 1
fi

echo "OK: unit-06 docker-overlay surfaces present"

# 7. Unit-07 terraform-overlay assertions.
echo "--- unit-07 terraform-overlay assertions ---"

# 7a. Tree shape: module + staging + staging2.example + new-terraform-env.sh.
for path in \
    "terraform/modules/SmokeApp-env/main.tf" \
    "terraform/modules/SmokeApp-env/variables.tf" \
    "terraform/modules/SmokeApp-env/dns.tf" \
    "terraform/modules/SmokeApp-env/cloud-init.yaml.tftpl" \
    "terraform/modules/SmokeApp-env/README.md" \
    "terraform/staging/main.tf" \
    "terraform/staging/versions.tf" \
    "terraform/staging/variables.tf" \
    "terraform/staging/outputs.tf" \
    "terraform/staging/rebootstrap.sh" \
    "terraform/staging/scripts/lint-cloud-init.sh" \
    "terraform/staging/test/cloudflare.tfvars" \
    "terraform/staging/.gitignore" \
    "terraform/staging2.example/main.tf" \
    "terraform/staging2.example/versions.tf" \
    "scripts/new-terraform-env.sh" \
    "docs/staging-runbook.md"
do
    if [[ ! -f "${project_root}/${path}" ]]; then
        echo "FAIL: terraform overlay missing: ${path}" >&2
        exit 1
    fi
done

# 7b. Token substitution sanity — no scaffold-time tokens leftover.
if grep -rnE '\$\{(PROJECT_NAME|PROJECTNAME_UPPER|GITHUB_OWNER|HCP_ORG|HETZNER_LOCATION|HETZNER_SERVER_TYPE|CLOUDFLARE_ZONE)' \
        "${project_root}/terraform/" \
        "${project_root}/scripts/new-terraform-env.sh" \
        "${project_root}/docs/staging-runbook.md" 2>/dev/null; then
    echo "FAIL: unsubstituted scaffold tokens in terraform overlay" >&2
    exit 1
fi

# 7c. Resource-name substitution: hcloud_* resources carry smokeapp- prefix.
for tf_file in \
    "terraform/modules/SmokeApp-env/vm.tf" \
    "terraform/modules/SmokeApp-env/firewall.tf"
do
    if ! grep -qE 'name *= *"smokeapp-' "${project_root}/${tf_file}"; then
        echo "FAIL: ${tf_file} missing smokeapp- prefix in resource names" >&2
        exit 1
    fi
done

# 7d. HCP workspace name matches PROJECT_NAME_LOWER.
if ! grep -q 'name = "smokeapp-staging"' "${project_root}/terraform/staging/versions.tf"; then
    echo "FAIL: staging versions.tf missing 'name = \"smokeapp-staging\"' HCP workspace" >&2
    exit 1
fi
if ! grep -q 'organization = "codarteinc"' "${project_root}/terraform/staging/versions.tf"; then
    echo "FAIL: staging versions.tf missing 'organization = \"codarteinc\"' (HCP_ORG default-from github_owner)" >&2
    exit 1
fi

# 7e. dns_provider default is "none".
if ! grep -qE 'default *= *"none"' "${project_root}/terraform/modules/SmokeApp-env/variables.tf"; then
    echo "FAIL: module variables.tf missing dns_provider default=\"none\"" >&2
    exit 1
fi

# 7f. Scripts are executable.
for script in \
    "terraform/staging/rebootstrap.sh" \
    "terraform/staging/scripts/lint-cloud-init.sh" \
    "scripts/new-terraform-env.sh"
do
    if [[ ! -x "${project_root}/${script}" ]]; then
        echo "FAIL: ${script} is not executable" >&2
        exit 1
    fi
done

# 7g. .gitignore carries the wildcard terraform block (post-splice).
if ! grep -qF 'terraform/**/.terraform/' "${project_root}/.gitignore"; then
    echo "FAIL: .gitignore missing wildcard terraform block (splice failed?)" >&2
    exit 1
fi
if ! grep -qF '!terraform/**/test/*.tfvars' "${project_root}/.gitignore"; then
    echo "FAIL: .gitignore missing test-tfvars allowlist" >&2
    exit 1
fi

# 7h. Optional terraform fmt + validate (CLI-gated).
if command -v terraform >/dev/null; then
    ( cd "$project_root" && terraform fmt -check -recursive terraform/ ) \
        || { echo "FAIL: terraform fmt -check -recursive failed" >&2; exit 1; }
    ( cd "$project_root/terraform/modules/SmokeApp-env" && \
        terraform init -backend=false -input=false -no-color > /dev/null && \
        terraform validate -no-color ) \
        || { echo "FAIL: module init+validate failed" >&2; exit 1; }
    ( cd "$project_root/terraform/staging" && \
        terraform init -backend=false -input=false -no-color > /dev/null && \
        terraform validate -no-color ) \
        || { echo "FAIL: staging init+validate failed" >&2; exit 1; }
    echo "OK: terraform fmt + validate clean"
else
    echo "SKIP: terraform not on PATH; fmt+validate skipped"
fi

echo "OK: unit-07 terraform-overlay surfaces present"

# 8. Unit-08 github-workflows-overlay assertions.
echo "--- unit-08 github-workflows assertions ---"

# 8a. All 14 expected files present.
declare -a workflow_files=(
    ".github/dependabot.yml"
    ".github/workflows/cicd.yml"
    ".github/workflows/dependabot-auto-merge.yml"
    ".github/workflows/runner-cache-cleanup.yml"
    ".github/workflows/staging-deploy.yml"
    ".github/workflows/staging-rollback.yml"
    ".github/workflows/_terraform-apply.yml"
    ".github/workflows/_terraform-plan.yml"
    ".github/workflows/_terraform-drift.yml"
    ".github/workflows/_terraform-destroy.yml"
    ".github/workflows/staging-terraform-apply.yml"
    ".github/workflows/staging-terraform-plan.yml"
    ".github/workflows/staging-terraform-drift.yml"
    ".github/workflows/staging-terraform-destroy.yml"
)
for f in "${workflow_files[@]}"; do
    if [[ ! -f "${project_root}/${f}" ]]; then
        echo "FAIL: workflow file missing: ${project_root}/${f}" >&2
        exit 1
    fi
done

# 8b. Every workflow YAML parses via yq.
for f in "${workflow_files[@]}"; do
    if ! yq eval '.' "${project_root}/${f}" > /dev/null 2>&1; then
        echo "FAIL: ${f} not valid YAML (yq parse failed)" >&2
        exit 1
    fi
done

# 8c. No LinkHub / codarteinc residue.
if grep -RIl -i 'linkhub\|codarteinc' "${project_root}/.github/" 2>/dev/null; then
    echo "FAIL: LinkHub residue in ${project_root}/.github/" >&2
    exit 1
fi

# 8d. cicd.yml references SmokeApp.slnx.
if ! grep -q 'SmokeApp\.slnx' "${project_root}/.github/workflows/cicd.yml"; then
    echo "FAIL: cicd.yml missing SmokeApp.slnx reference" >&2
    exit 1
fi

# 8e. staging-deploy.yml references smokeapp-{api,web,dbmigrator}.
for img in smokeapp-api smokeapp-web smokeapp-dbmigrator; do
    if ! grep -q "${img}" "${project_root}/.github/workflows/staging-deploy.yml"; then
        echo "FAIL: staging-deploy.yml missing image reference ${img}" >&2
        exit 1
    fi
done

# 8f. Concurrency-group contract — the 4 shared-group workflows.
group_deploy=$(yq -r '.concurrency.group' "${project_root}/.github/workflows/staging-deploy.yml")
group_rollback=$(yq -r '.concurrency.group' "${project_root}/.github/workflows/staging-rollback.yml")
group_apply=$(yq -r '.jobs.apply.with.concurrency_group' "${project_root}/.github/workflows/staging-terraform-apply.yml")
group_destroy=$(yq -r '.jobs.destroy.with.concurrency_group' "${project_root}/.github/workflows/staging-terraform-destroy.yml")
if [[ "$group_deploy" != "smokeapp-staging-deploy" \
   || "$group_rollback" != "smokeapp-staging-deploy" \
   || "$group_apply" != "smokeapp-staging-deploy" \
   || "$group_destroy" != "smokeapp-staging-deploy" ]]; then
    echo "FAIL: concurrency-group drift: deploy=$group_deploy rollback=$group_rollback apply=$group_apply destroy=$group_destroy" >&2
    exit 1
fi

# 8g. actionlint (if installed) clean.
if command -v actionlint >/dev/null; then
    if ! actionlint -no-color -shellcheck= "${project_root}/.github/workflows/"*.yml; then
        echo "FAIL: actionlint reported errors" >&2
        exit 1
    fi
fi

echo "OK: unit-08 github-workflows surfaces present + structurally valid"

echo "OK: smoke test passed (solution at ${sln}; build log at ${smoke_dir}/build.log)"
